"use client";
import {use,useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
const assetHost="https://zayd-architecture-portfolio.accgo-2651.chatgpt.site";
const data={
"private-residence":{title:"PRIVATE RESIDENCE",ar:"منزل خاص",label:"PROJECT RECORD · سجل المشروع",hero:"/residence/brand/hero-house.webp",kicker:"Construction Chronicle",headline:"From groundwork to final form.",intro:"A curated visual record of a private residence, documented from the first foundation lines to the final architectural reveal.",introAr:"سجل بصري مختار لمنزل خاص، يوثّق الرحلة من أول خطوط الأساسات حتى الكشف المعماري النهائي.",stats:[["10 × 20 m","Plot"],["200 m²","Area"],["2","Floors"],["07","Stages"],["82","Images"]],finalTitle:"The finished home, revealed from every angle.",finalAr:"الرؤية التصميمية النهائية",finalText:"Three exterior studies reveal the final composition, material balance and street presence.",final:[[`${assetHost}/residence/final-renders/street-elevation.webp`,"Street Elevation","الواجهة من الشارع"],[`${assetHost}/residence/final-renders/elevated-view.webp`,"Elevated View","المنظور المرتفع"],[`${assetHost}/residence/final-renders/low-angle-detail.webp`,"Low-Angle Detail","تفاصيل من زاوية منخفضة"]],before:`${assetHost}/residence/comparison/before-house-shell.webp`,after:"/residence/brand/hero-house.webp",compare:"From first lines to final form.",planTitle:"The plan behind the build.",plans:[[`${assetHost}/residence/project-plans/ground-floor.webp`,"Ground Floor"],[`${assetHost}/residence/project-plans/first-floor.webp`,"First Floor"]],stages:["Foundations & Substructure","Reinforced Concrete Structure","Masonry & Services Rough-In","Insulation & MEP Integration","Surface Preparation & Tilework","Facade & Interior Finishes","Flooring & Final Reveal"]},
"private-indoor-pool":{title:"PRIVATE INDOOR POOL",ar:"مسبح داخلي خاص",label:"INTERIOR PROJECT · المشروع الداخلي",hero:"/pool/renders/hero.webp",kicker:"Interior Construction Story",headline:"Water, light, and stillness.",intro:"A private indoor pool followed from the first excavation to its completed atmosphere of blue mosaic, warm stone, and reflected light.",introAr:"مسبح داخلي خاص نوثّق رحلته من أول أعمال الحفر حتى اكتمال أجوائه من الموزاييك الأزرق والحجر الدافئ والضوء المنعكس.",stats:[["Duhok","Location"],["Indoor","Type"],["05","Stages"],["23","Images"],["2026","Year"]],finalTitle:"The finished interior, shaped by water.",finalAr:"الرؤية التصميمية النهائية",finalText:"The final views bring together the axial composition, water surface, feature cascade, and mirrored ceiling.",final:[["/pool/renders/hero.webp","Axial Pool View","المنظور المحوري للمسبح"],["/pool/renders/full-room.webp","Interior Atmosphere","أجواء الفراغ الداخلي"],["/pool/renders/water-detail.webp","Water & Light Detail","تفاصيل الماء والإضاءة"]],before:"/pool/comparison/before-private-pool.webp",after:"/pool/renders/hero.webp",compare:"From concrete shell to calm retreat.",planTitle:"Measured before execution.",plans:[["/pool/plans/pool-plan.webp","Rendered Pool Plan · Scale 1:100"],["/pool/concept/material-board.webp","Material & Atmosphere Board"]],stages:["Excavation & Structural Shell","Waterproofing & Service Coordination","Pool Tiling & Stonework","Ceiling, Lighting & Interior Finishes","Commissioning & Final Reveal"]}} as const;
const stageImages={
"private-residence":[
["c001","c002","c003","b006","b008","b011","b012","b013","b014","b015","b018","b020","b023","b024"],
["b005","a001","a002","a003","a004","a005","a008","a009","a010","a013","a016","a021"],
["a023","a026","a027","a029","a030","a031","a032","a033","a034","a035","a036"],
["b001","b002","b004","a037","a039","a040","a042","a045","a046","a047","a048","a051","a052"],
["a054","a055","a056","a057","a058","a059","a060","a061","a062","a063","a064","a065","a072"],
["a074","a076","a077","a079","a080","a081","a082","a084","a085","a086","a087"],
["a090","a092","a093","a094","a095","a098","a099","a100"]],
"private-indoor-pool":[["p001","p002","p003","p004","p005"],["p101","p102","p103","p104","p105"],["p201","p202","p203","p204","p205"],["p301","p302","p303","p304"],["p401","p402","p403","p404"]]
} as const;
export default function Project({params}:{params:Promise<{slug:string}>}){const{slug}=use(params),p=data[slug as keyof typeof data],search=useSearchParams();const[x,setX]=useState(50),[lightbox,setLightbox]=useState<{src:string;alt:string}|null>(null),showStages=search.get("from")!=="home";useEffect(()=>{const close=(e:KeyboardEvent)=>e.key==="Escape"&&setLightbox(null);window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);if(!p)return <main className="project-page"><h1>Project not found</h1></main>;const preview=(src:string,alt:string)=>setLightbox({src,alt});return <main className={`project-page ${slug.includes("pool")?"pool":""}`}><header className="project-top"><a className="brand" href="/"><img src="/deluxe-logo.png" alt=""/><span><strong>DELUXE</strong><b>ENGINEERING</b></span></a><a href="/">CLOSE PROJECT ✕</a></header><section className="project-hero"><img className="previewable" onClick={()=>preview(p.hero,p.title)} src={p.hero} alt={p.title}/><div className="project-hero-copy"><p>{p.label}</p><h1>{p.title}</h1><h2 dir="rtl">{p.ar}</h2></div></section>
<section className="project-intro"><div><p className="kicker">{p.kicker}</p><h2>{p.headline}</h2><h3 dir="rtl">{p.ar}</h3></div><div><p>{p.intro}</p><p dir="rtl">{p.introAr}</p></div><div className="stats">{p.stats.map(s=><div key={s[1]}><b>{s[0]}</b><small>{s[1]}</small></div>)}</div></section>
<section className={`project-section ${slug.includes("pool")?"blue":"dark"}`}><p className="kicker">{p.finalAr}</p><h2>{p.finalTitle}</h2><p className="lead">{p.finalText}</p><div className="gallery">{p.final.map(f=><figure key={f[1]}><img className="previewable" onClick={()=>preview(f[0],f[1])} src={f[0]} alt={f[1]}/><figcaption><b>{f[1]}</b><small dir="rtl">{f[2]}</small></figcaption></figure>)}</div></section>
<section className="project-section"><p className="kicker">Before / Final</p><h2>{p.compare}</h2><p className="lead">Move the divider to compare the unfinished shell with the completed architectural result.</p><div className={`comparison ${slug==="private-residence"?"comparison-contain":""}`}><img src={p.after} alt="Final result"/><img className="before" style={{clipPath:`inset(0 ${100-x}% 0 0)`}} src={p.before} alt="Before construction"/><input aria-label="Before and after comparison" type="range" min="5" max="95" value={x} onChange={e=>setX(+e.target.value)}/><div className="comparison-preview"><button onClick={()=>preview(p.before,"Before construction")}>View full before</button><button onClick={()=>preview(p.after,"Final result")}>View full final</button></div></div></section>
<section className="project-section"><p className="kicker">Project drawings · مخططات المشروع</p><h2>{p.planTitle}</h2><div className="plans">{p.plans.map(f=><figure key={f[1]}><img className="previewable" onClick={()=>preview(f[0],f[1])} src={f[0]} alt={f[1]}/><figcaption><b>{f[1]}</b></figcaption></figure>)}</div></section>
{showStages&&<section className="project-section dark"><p className="kicker">Construction journey · رحلة الإنشاء</p><h2>Built in documented stages.</h2><div className="timeline">{p.stages.map((s,i)=><a href={`#stage-${i+1}`} key={s}>0{i+1} · {s}</a>)}</div>{p.stages.map((s,i)=><article className="stage" id={`stage-${i+1}`} key={s}><p className="kicker">Construction Stage · 0{i+1}</p><h2>{s}</h2><p className="lead">A visual site record documenting the materials, coordination, workmanship, and progress of this stage.</p><div className="construction-gallery">{stageImages[slug as keyof typeof stageImages][i].map((name,j)=>{const src=slug==="private-residence"?`${assetHost}/residence/photos/thumbs/${name}.webp`:`/pool/construction/thumbs/${name}.webp`;return <figure key={name}><img className="previewable" onClick={()=>preview(src,`${s} — construction record ${j+1}`)} src={src} alt={`${s} — construction record ${j+1}`} loading="lazy"/><figcaption><span>0{i+1}.{String(j+1).padStart(2,"0")}</span><b>{s}</b></figcaption></figure>})}</div></article>)}</section>}
<section className="project-cta"><p>Start a conversation · ابدأ المحادثة</p><h2>Have a similar project?</h2><h3 dir="rtl">هل لديك مشروع مشابه؟</h3><a href={`https://wa.me/9647509012525?text=${encodeURIComponent(`Hello Deluxe Engineering, I would like to discuss a project similar to ${p.title}.`)}`}>Contact Deluxe Engineering ↗</a></section>{lightbox&&<div className="image-lightbox" role="dialog" aria-modal="true" aria-label="Full-size image preview" onClick={()=>setLightbox(null)}><button className="lightbox-close" onClick={()=>setLightbox(null)} aria-label="Close image preview">✕</button><img src={lightbox.src} alt={lightbox.alt} onClick={e=>e.stopPropagation()}/><p>{lightbox.alt}</p></div>}</main>}
