"use client";
import {useState} from "react"; import {useRouter} from "next/navigation";
const projects=[
{n:"01",title:"Private Residence",ar:"منزل خاص",type:"Construction Journey",image:"/projects/private-residence.webp",href:"/projects/private-residence",place:"Duhok · Masike"},
{n:"02",title:"Private Indoor Pool",ar:"مسبح داخلي خاص",type:"Interior Architecture",image:"/pool/renders/wheel.webp",href:"/projects/private-indoor-pool",place:"Duhok, Iraq"},
{n:"03",title:"Residential Tower",ar:"برج سكني",type:"Architecture",image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=88",place:"Erbil, Iraq"},
{n:"04",title:"Commercial Center",ar:"مركز تجاري",type:"Mixed Use",image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=88",place:"Duhok, Iraq"},
{n:"05",title:"Landscape",ar:"تنسيق الموقع",type:"Outdoor Design",image:"https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=88",place:"Kurdistan Region"},
{n:"06",title:"Urban Masterplan",ar:"مخطط حضري رئيسي",type:"Planning",image:"https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1200&q=88",place:"Iraq"},
{n:"07",title:"Interior Design",ar:"التصميم الداخلي",type:"Interiors",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=88",place:"Duhok, Iraq"},
{n:"08",title:"Corporate Offices",ar:"مكاتب إدارية",type:"Workplace",image:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=88",place:"Kurdistan Region"},
{n:"09",title:"Hospitality Concept",ar:"مفهوم ضيافة",type:"Hospitality",image:"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=88",place:"Iraq"}];
export default function Home(){const[a,setA]=useState(0),r=useRouter(),p=projects[a];const move=(d:number)=>setA((a+d+9)%9),open=()=>p.href&&r.push(`${p.href}?from=home`);return <main>
<section className="hero" id="home"><header className="site-header"><Brand/><nav><a href="#home">Home<small>الرئيسية</small></a><a href="#projects">Projects<small>المشاريع</small></a><a href="#services">Services<small>الخدمات</small></a><a href="#about">About<small>من نحن</small></a><a href="#contact">Contact<small>تواصل</small></a></nav><a className="outline-button" href="#contact">Start a project<small>ابدأ مشروعك</small></a></header>
<div className="hero-copy"><p className="eyebrow">ARCHITECTURE <i/> ENGINEERING <i/> VISUALIZATION</p><h1>Engineering Ideas Into Reality</h1><h2 dir="rtl">نحوّل الأفكار الهندسية إلى واقع</h2><p>Rotate the gear to explore our selected works.<small dir="rtl">دوّر الترس لاستكشاف مجموعة من أعمالنا المختارة.</small></p><div className="hint">↔ Drag to rotate · Click to view</div><button className="view-project" onClick={open} disabled={!p.href}><span><b>{p.href?"Open project journey":"Coming soon"}</b><small>{p.href?"افتح رحلة المشروع":"قريباً"}</small></span><em>↗</em></button></div>
<div className="gear-stage" id="projects"><div className="selected-caption"><span>{p.n}</span><p>{p.type}<small>{p.href?"Documented Project":"Coming Soon"}</small></p></div><button className="rotate-control left" onClick={()=>move(-1)}>←</button><div className="gear"><button className="active-card" onClick={open}><img src={p.image} alt=""/><span>{p.n}</span><div><small>{p.type}</small><strong>{p.title}</strong><b dir="rtl">{p.ar}</b><em>{p.href?"VIEW PROJECT":"COMING SOON"}</em></div></button><img className="hub" src="/deluxe-logo.png" alt="Deluxe Engineering"/></div><button className="rotate-control right" onClick={()=>move(1)}>→</button><div className="dots">{projects.map((x,i)=><button key={x.n} className={i===a?"on":""} onClick={()=>setA(i)} aria-label={`Show ${x.title}`}/>)}</div></div>
<div className="mobile-track">{projects.map(x=><button key={x.n} onClick={()=>x.href&&r.push(`${x.href}?from=home`)}><img src={x.image} alt=""/><span>{x.n}</span><div><small>{x.type}</small><strong>{x.title}</strong><b dir="rtl">{x.ar}</b><em>{x.place}</em></div></button>)}</div></section>
<section className="light-section" id="services"><Kicker n="01" en="Capabilities" ar="خدماتنا"/><div className="split-heading"><h2>One studio.<br/>Every project layer.<small dir="rtl">استوديو واحد.<br/>لكل مراحل المشروع.</small></h2><div><p>From the first line on paper to the final visual, our disciplines work together to make ambitious ideas buildable.</p><p dir="rtl">من أول خط على الورق حتى الصورة النهائية، تعمل تخصصاتنا معاً لتحويل الأفكار الطموحة إلى مشاريع قابلة للتنفيذ.</p></div></div><div className="service-grid"><Service n="01" icon="⌂" en="Architecture" ar="العمارة" text="Concept design, planning, façades, construction drawings and coordinated project delivery."/><Service n="02" icon="△" en="Engineering" ar="الهندسة" text="Clear structural thinking and technical coordination that turn a strong concept into a sound building."/><Service n="03" icon="◈" en="Visualization" ar="التصور المعماري" text="Atmospheric stills and presentations that communicate space, material and intent before construction."/></div></section>
<section className="about" id="about"><div className="about-mark"><img src="/deluxe-logo.png" alt=""/></div><div><Kicker n="02" en="The studio" ar="الاستوديو"/><h2>Precision in every line.<br/><em>Purpose in every space.</em></h2><h3 dir="rtl">دقة في كل خط. وغاية في كل مساحة.</h3><p>Deluxe Engineering brings architecture, technical thinking and visualization into one focused process. We design spaces that feel distinctive, perform intelligently and stand the test of time.</p><p dir="rtl">تجمع ديلوكس للهندسة بين العمارة والتفكير التقني والتصور البصري ضمن عملية واحدة مركزة، لنصمم مساحات مميزة وذكية تدوم مع الزمن.</p><div className="values"><b>Integrated<small>متكامل</small></b><b>Detailed<small>دقيق</small></b><b>Human<small>إنساني</small></b></div></div></section>
<section className="contact" id="contact"><Kicker n="03" en="Visit or contact us" ar="زرنا أو تواصل معنا"/><h2>Let’s build what’s next.</h2><h3 dir="rtl">لنَبْنِ الخطوة القادمة معاً.</h3><p>Architecture, engineering and construction in Duhok.</p><div className="contact-links"><a href="https://maps.app.goo.gl/o4aKMhR1BxwSQ9sQA">01 <span>Office location<small>Iraq · Duhok · Masike</small></span>↗</a><a href="https://www.instagram.com/aqaratdeluxe/">02 <span>Instagram<small>@aqaratdeluxe</small></span>↗</a><a href="tel:+9647509012525">03 <span>Phone<small>0750 901 2525</small></span>↗</a><a href="https://wa.me/9647509012525">04 <span>WhatsApp<small>0750 901 2525</small></span>↗</a></div></section><footer><Brand/><p>Architecture · Engineering · Visualization</p><a href="#home">Back to top ↑</a></footer></main>}
function Brand(){return <a className="brand" href="/"><img src="/deluxe-logo.png" alt=""/><span><strong>DELUXE</strong><b>ENGINEERING</b></span></a>};function Kicker({n,en,ar}:{n:string,en:string,ar:string}){return <p className="kicker"><span>{n}</span>{en}<small dir="rtl">{ar}</small></p>};function Service({n,icon,en,ar,text}:{n:string,icon:string,en:string,ar:string,text:string}){return <article><span>{n}</span><i>{icon}</i><h3>{en}<small dir="rtl">{ar}</small></h3><p>{text}</p></article>}
